- name: Check given number is greater than 10 or not.
  hosts: local
  connection: local
  vars:
    my_number: 14
  tasks:
  - name: Print if the number is greater than 10.
    ansible.builtin.debug:
      msg: "The given number {{my_number}} is greater than 10"
    when: my_number > 10