- name: Create expense user if not exists
  hosts: WEB
  tasks:
  - name: Checking expense user is already available or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: True #errror handling , will handle this error in other task
  
  - name: Print info
    ansible.builtin.debug:
      msg: "expense user exists in server"
    when: USER.rc ==0
  
  - name: Creating expense user if not exists..
    ansible.builtin.command: useradd expense
    when: USER.rc !=0