- name: Check weather expense user exists or not
  hosts: WEB
  tasks:
  - name: Checking expense user is already available or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: True #errror handling , will handle this error in other task
  
  - name: Print info
    ansible.builting.debug:
      msg: "{{USER}}"