- name: Check weather expense user exists or not
  hosts: WEB
  tasks:
  - name: Checking expense user is already available or not
    ansible.builtin.command: id expense
    register: USER #here USER variable stores the output of the above command.
    ansible.builtin.debug:
      msg: "Info {{USER}}"