- name: Ansible Filters usage
  hosts: local
  #connection: local
  vars:
    course: "Aws devops"
  tasks:
  - name: Giving default value for variable
    ansible.builtin.debug:
      msg: "{{course}}"