- name: Ansible Filters usage
  hosts: local
  connection: local
  tasks:
  - name: Giving default value for variable
    ansible.builtin.debug:
      msg: "{{course | default ('ansible course')}}"

  - name: Using unique filter to get a unique number from given list
    vars:
      my_num: [1,2,3,5,5,6,6,7,7,8]
    ansible.builtin.debug:
      msg: "{{my_num | ansible.builtin.unique}}"

  - name: Using min and max filters
    vars:
      my_num: [10,2,3,55,0,13]
    ansible.builtin.debug:
      msg: "Min: {{ my_num | min }} max: {{ my_num | max }}"
  - name: convert string to upper case
    vars:
      my_str: "hello Srikanth"
    ansible.builtin.debug:
      msg: "{{ my_str | upper }}"
  - name: covert string to lower case
    vars:
      greeting: "Good Moring All"
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

  - name: dictionary to items
    vars:
      courses:
        name: "AWS"
        duration: 120
        trainer: "Siva"
    ansible.builtin.debug:
      msg: "{{courses | dict2items }}"

  